### DISCUSSION TITLE
Kein Download von voice messages

### DISCUSSION THREAD

**Discussion by Eigeplackter** [Ludy87/xplora_watch#440] [Q&A]
Ja leider ich schon wieder  ;-)

Ich betreibe HA innerhalb einer VMware® Workstation 17 Pro Version: 17.5.2 build-23775571
Core 2024.8.1 / Supervisor 2024.08.0 / Operating System 12.4 /Frontend 20240809.0

[Hier](https://github.com/Ludy87/xplora_watch/tree/main?tab=readme-ov-file#downloaded-from-voice-messages-videos-and-images-v270) heißt es:

> All voice messages, videos and images are stored in config/www/{voice|video|image|}

Klar ist mir config/www/voice und config/www/video und config/www/image

Nun habe ich eine voice message mit Link

http://IP.MEINER.VM.HA:8123/local/voice/19adc08e96de57709cbb0d9bb7a75ddc.mp3

In der configuration.yaml habe ich folgendes:

```YAML
  media_dirs:
    local: /config/www
    voice: /config/www/voice
    video: /config/www/video
    image: /config/www/image
```

Ich kann die Ordner auch über Medien öffnen, aber die mp3 ist nicht auffindbar.

Kann es sein, das diese Funktion nur gegeben ist, wenn man HA auf bare metal betreibt (Raspi,etc.) ?
