### ISSUE TITLE
Multiple watches on single account

### ISSUE THREAD

**Issue by arvidarvidarvid** [Ludy87/xplora_watch#11]
Thanks for creating this integration! 

I have two watches attached to my xplora account and only the first one ends up being mapped to entities. Is this a known limitation or should I debug?

**Comment by Ludy87** [comment]
hi, moment it's just a single mode, i need to understand how to distinguish multiple clocks. Unfortunately I can't test this, I only have one watch.

**Comment by Ludy87** [comment]
@arvidarvidarvid check https://github.com/Ludy87/xplora_watch/releases/tag/v0.0.15-Beta for multiple watches

```yaml
xplora_watch:
  country_code: "+49"
  phonenumber: "123456789"
  password: "password"
  userlang: "de-DE"
  timezone: "Europe/Berlin"
  child_phonenumber:
    - "9876543210" # new
    - "5678901234" # new
  types:
    - "battery"
    - "xcoin"
    - "state"
    - "safezone"
    - "charging"
    - "silents"
    - "alarms"
    - "dt_watch"
  safezones: "show"
  scan_interval: 180 # default sec
  tracker_scan_interval: 60 # default sec
```
