### ISSUE TITLE
Battery drainage

### ISSUE THREAD

**Issue by Puddingpanzer** [Ludy87/xplora_watch#15]
Hi, I appreciate your work and the integration works like charm but the battery drainage is enormous on our Xplora3 watch, even if the watch is not in use and if I set the intervals to 30 minutes or so. Do you have any tips to reduce that with configuration variables? Is it possible to set the intervals to 0 and scan manually via device_tracker.see on demand?

![image](https://user-images.githubusercontent.com/97258056/155705289-5740baab-2a74-4b49-9bc4-799fce7d25e6.png)

**Comment by Ludy87** [comment]
Hi, I would check if I can set a switch that allows the tracking to be switched on manually.

**Comment by Puddingpanzer** [comment]
Thanks for your quick support :) Grüße aus Deutschland

**Comment by Ludy87** [comment]
@Puddingpanzer schau dir die Veränderung an, ob es so passt.

**Comment by Puddingpanzer** [comment]
> @Puddingpanzer schau dir die Veränderung an, ob es so passt.

Sieht gut aus, ich bin gespannt ob es die Lebenszeit der Uhr verlängert.

**Comment by Ludy87** [comment]
Den Helfer erstellen mit der Entity-ID `input_boolean.xplora_tracker_switch`, damit kannst du dann den Tracker deaktivieren, ohne die Conf zu bearbeiten.

**Comment by Puddingpanzer** [comment]
Der Switch funktioniert soweit. Es wird nicht automatisch getracked aber die restlichen Daten wie z.B. Akkustatus werden dennoch geladen. Allerdings kann ich die Uhr jetzt nicht manuell per device_tracker.see tracken solange der switch auf off steht, die Koordinaten aktualisieren sich dann nicht.

**Comment by Ludy87** [comment]
Ja, das ist die Krux entweder an oder aus, ich behalte das auf dem Schirm, bis mir was besseres einfällt.

Track und Sensoren sind zwei Paar Schuhe

**Comment by Puddingpanzer** [comment]
Dann wäre es evtl. einfacher das Intervall auf 0 oder sehr hoch bspw. 24 Stunden zu setzen und dann zwischendurch manuell zu tracken? Oder gibt es Grenzwerte für die Intervalle?

**Comment by Ludy87** [comment]
Ich habe bei mir 3600 Sekunden und das funktioniert, eine Grenze ist mir nicht bekannt

**Comment by Puddingpanzer** [comment]
Ich habe mir jetzt ein Script gebaut was ich manuell ausführen kann. Tracker Intervall steht auf 60 Sekunden, der Switch standardmäßig auf off. Bei Ausführung des Scripts wird zuerst der Switch auf on gestellt und nach 60 Sekunden wieder auf off. Funktioniert soweit.

**Comment by Ludy87** [comment]
Hi, kannst du das hier bereitstellen, dann kann ich es als Beispiel mit einpflegen

**Comment by Puddingpanzer** [comment]
Klar, bin kein Script-Experte aber das sollte gehen. Das setzt voraus dass das Tracker-Intervall auf 60 Sek. eingestellt ist.

```yaml
standort_laden:
  alias: Standort laden
  sequence:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.xplora_tracker_switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.xplora_tracker_switch
  mode: single
```
