### ISSUE TITLE
xplora_watch.send_message does not seem to support templates

### ISSUE THREAD

**Issue by DIYtechie** [Ludy87/xplora_watch#352]
### What version of Integration has the issue?

2.12.1

## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4806
Installed Version | 1.33.0
Stage | running
Available Repositories | 1371
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 23, 2024 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
instance_id | 48b30477ee8044d3a9ae02b2611a030e
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 916.2 GB
disk_used | 12.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.12.5), File editor (5.7.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Node-RED (17.0.2), Terminal & SSH (9.8.1), deCONZ (6.22.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 16
views | 31
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 4, 2024 at 6:54 AM
-- | --
current_recorder_run | January 13, 2024 at 9:38 AM
estimated_db_size | 695.33 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 0 / 8
local_online | 2 / 2
debug | failed to load: 

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Since I cannot be logged into the app and the integration at the same time, I'm using Home Assistant to send and receive messages from my son. I use an input_text helper (called input_text.xplora_message) or the data message field, but when I try to send the input helper text via the xplora_watch.send_message service using {{ states('input_text.xplora_message') }} my son only receives the name of the input text helper and not the contents of the helper.

### Reproduction steps

create a input text helper. Could be called: input_text.xplora_message

Change the text to something. E.g. "hello"

Then using developer tools try this

```
service: xplora_watch.send_message
data:
  target: 79637893468937465
  message: '{{ states('input_text.xplora_message') }}'
  user: 7364587365879
```

### Debug logs

```text
no errors, the issue is that the template is not recognized but simply sent as text
```

**Comment by DIYtechie** [comment]
Apparently, it works if I do the exact same via a script instead of the developer tools. 

i.e. This works:

```
alias: send xplora message
sequence:
  - service: xplora_watch.send_message
    metadata: {}
    data:
      target: 7836847637486
      user: 874563784563857678
      message: "{{ states('input_text.xplora_message') }}"
mode: single
```
